
all:
	$(MAKE) -C validate
	$(MAKE) -C parse-string
	$(MAKE) -C push-pop-string
	$(MAKE) -C callback-string
	$(MAKE) -C caller-string
	$(MAKE) -C parse-file
	$(MAKE) -C push-pop-file
	$(MAKE) -C callback-file
	$(MAKE) -C caller-file
	$(MAKE) -C builder

clean:
	$(MAKE) -C validate clean
	$(MAKE) -C parse-string clean
	$(MAKE) -C push-pop-string clean
	$(MAKE) -C callback-string clean
	$(MAKE) -C caller-string clean
	$(MAKE) -C parse-file clean
	$(MAKE) -C push-pop-file clean
	$(MAKE) -C callback-file clean
	$(MAKE) -C caller-file clean
	$(MAKE) -C builder clean
