
all:
	make -C validate
	make -C parse-string
	make -C push-pop-string
	make -C callback-string
	make -C caller-string
	make -C parse-file
	make -C push-pop-file
	make -C callback-file
	make -C caller-file
	make -C builder

clean:
	make -C validate clean
	make -C parse-string clean
	make -C push-pop-string clean
	make -C callback-string clean
	make -C caller-string clean
	make -C parse-file clean
	make -C push-pop-file clean
	make -C callback-file clean
	make -C caller-file clean
	make -C builder clean
